/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unistrong_barcodetest_BarcodeNative */

#ifndef _Included_com_unistrong_barcodetest_BarcodeNative
#define _Included_com_unistrong_barcodetest_BarcodeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unistrong_barcodetest_BarcodeNative
 * Method:    initUart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_unistrong_barcodetest_BarcodeNative_initUart
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_unistrong_barcodetest_BarcodeNative
 * Method:    exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_unistrong_barcodetest_BarcodeNative_exit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_unistrong_barcodetest_BarcodeNative
 * Method:    get
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_unistrong_barcodetest_BarcodeNative_get
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_unistrong_barcodetest_BarcodeNative
 * Method:    scan
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_unistrong_barcodetest_BarcodeNative_scan
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
